#! /usr/bin/bash

#****COLORS****
LRED="\e[91m"
RED="\e[31m"
LGREEN="\e[92m"
YELLOW="\e[33m"
LYELLOW="\e[93m"
LMAGENTA="\e[95m"
LCYAN="\e[96m"
LGRAY="\e[37m"
DGRAY="\e[90m"
BLACK="\e[30m"
NC="\e[0;39m"

#*****INTRO*****
printf " \n \
${LGRAY}             XXXX${DGRAY}XXXX\n \
${LGRAY}         XXXXXXXX${DGRAY}XXXXXXXX\n \
${LGRAY}       XXXXXXXXXX${DGRAY}XXXXXXXXXX\n \
${LGRAY}      XXXXXXXXXXX${DGRAY}XXXXXXXXXXX${LYELLOW}X${NC}\n \
${LGRAY}    XXXXXXXXXXXXX${DGRAY}XXXXXXXXXXXX${LYELLOW}X${NC}\n \
${LGRAY}   XXXXXXXXXXXXXX${DGRAY}XXXXXXXXXXXX${LYELLOW}XXX${NC}\n \
${LGRAY}  XX             ${DGRAY}XXXXXXXXXXXX${LYELLOW}XXX${NC}\n \
${LGRAY}  XX             ${DGRAY}XXXXXXXXXXXX${LYELLOW}XXX${NC}\n \
${LGRAY}   XXXXXXXXXXXXXX${DGRAY}XXXXXXXXXXXX${LYELLOW}XX${NC}\n \
${LGRAY}      XXXXXXXXXXX${DGRAY}XXXXXXXXXXXX${LYELLOW}XX${NC}\n \
${LGRAY}       XXXXXXXXXX${DGRAY}XXXXXXXXXX${LYELLOW}XXX${NC}\n \
${LGRAY}        XXXX     ${LYELLOW}XXXXXXXXXXXX${NC}\n \
${LGRAY}          XXXXXXX${LYELLOW}XXXXXXXXXX${NC}\n \
${LGRAY}             XXXX${LYELLOW}XXXXXXX${NC}\n \
_________________________________\n
\n"